spring:
  application:
    name: api-gateway
  cloud:
    config:
      uri: http://localhost:8888
  config:
    import: configserver:http://localhost:8888

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    reactor.netty: INFO
